### PR TITLE
Standardize logging and minor improvements

### PR DESCRIPTION
**Pull request by mchurichi**
Signed-off-by: Maximiliano Churichi <mchurichi@gmail.com>

**Pull Request check list**

- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**
Standardizes loggers and removes Echo banners

**Which issue this PR fixes**

### CODE REVIEW

**Review by jufantozzi — COMMENTED** [review]
I have only one comment, very nitpicky, but slightly _based_:
`Log/log > Logger/logger`

my arguments in favor are essentially:
1. this is a very personal one, but to me `logger.bla` reads better than `log.bla`;
2. many logging libraries, including `logrus` have their log object called "logger";
3. echo library has `.Logger()` method which we kinda have to use, to it would not be fully standarized.

**Comment by mchurichi** [comment]
> I have only one comment, very nitpicky, but slightly _based_: `Log/log > Logger/logger`
> 
> my arguments in favor are essentially:
> 
>     1. this is a very personal one, but to me `logger.bla` reads better than `log.bla`;
> 
>     2. many logging libraries, including `logrus` have their log object called "logger";
> 
>     3. echo library has `.Logger()` method which we kinda have to use, to it would not be fully standarized.

Alright, I'm ok with either `log` or `logger` as long as we stick to one. I chose `log` just because it's shorter and easier to read but I will change it if you feel strongly about it. The only topic I disagree is the use of echo's Logger, as we should use our own to avoid logging formatting/configuration differences.

**Comment by jufantozzi** [comment]
@mchurichi yup, that sounds good

**Review by jufantozzi — APPROVED** [review]
Thanks @mchurichi, this is great!

**Review by jufantozzi — APPROVED** [review]

**Review by mgbcaio — APPROVED** [review]
Thanks for that! 🍈

**Review by maxlambrecht — APPROVED** [review]
Nice! 🍰 

I prefer `logger` too.

**Comment by mchurichi** [comment]
on hold until we get #52 merged

**Comment by mchurichi** [comment]
This is now ready for review

**Review by maxlambrecht — APPROVED** [review]

**Pull request merged**
